version = 0
app_configs = [
	{"path" = "jakewilkins", "client_id" = "Iv1.dd5706e72cfeb9d8"},
  {"path" = "not-github", "client_id" = "Iv1.0d8235be0345f60f"},
  {"path" = "jakes-fine-avocados", "client_id" = "Iv1.0d8235be0345f60f"}
]
fallback = "store --file $HOME/.config/git/.git-credentials"
credentials = []
