#!/bin/bash

function do_install() {
		echo "installing neovim"
		curl -L -o nvim.appimage https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage

		chmod u+x nvim.appimage

		./nvim.appimage --appimage-extract >/dev/null

		sudo mv squashfs-root /
		sudo ln -fs /squashfs-root/AppRun /usr/local/bin/nvim
		rm nvim.appimage
		hash -r
}

echo -n "Checking for neovim... "
hash nvim 2>/dev/null || do_install

# The apt installed version is 0.4.3, we'll just watch the minor version so they can
# bump the patch version.
minor_version=`nvim --version | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 2`

if [[ "$minor_version" == "4" ]]; then
	do_install
fi

echo "ok fine"
