#!/bin/bash

[ $(uname -s) = "Linux" ] && export LINUX=1
[ $(uname -s) = "Darwin" ] && export DARWIN=1

if hash brew 2>/dev/null; then
	echo "Brew is installed"
elif [ $LINUX ]; then
	echo "We're on Linux; install linuxbrew yourself if you want it. Skipping."
	exit 1
else
	echo "Installing homebrew"
	CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Installing global brew dependencies"

brew bundle --file ./homebrew/Brewfile

if [ $LINUX ]; then
	echo "Installing Linux dependencies"
	brew bundle --file homebrew/Brewfile.linux
elif [ $DARWIN ]; then
	echo "Installing Darwin dependencies"
	brew bundle --file homebrew/Brewfile.darwin
fi

if [ ! -f "$HOME/.fzf.zsh" ]; then
	$(brew --prefix)/opt/fzf/install --all --key-bindings --completion --no-update-rc --no-fish --no-bash
fi

