#!/bin/bash

pushd $HOME/.dotfiles

system=$(uname -s | tr '[:upper:]' '[:lower:]')
url="https://github.com/jakewilkins/git-credential-github-keychain/releases/download/release-4e9290713647c22519e43c4b49e70f9ce415fd79/$system-git-credential-github-keychain.zip"

curl -Lo credential-helper.zip "$url"
unzip credential-helper.zip
mv -v git-credential-github-keychain ./bin/
rm credential-helper.zip

popd
