#!/bin/bash

pushd $HOME/.dotfiles

latest_release_url=$(curl https://github.com/jakewilkins/git-credential-github-keychain/releases/latest --write-out '%{redirect_url}' -o /dev/null -s)
latest_release=$(echo $latest_release_url | cut -d '/' -f 8)
echo "Latest release:"
echo "'$latest_release'"
echo "System:"
system=$(uname -s | tr '[:upper:]' '[:lower:]')
echo $system
#https://github.com/jakewilkins/git-credential-github-keychain/releases/download/release-f7b4495e1172f1d89c8c305162e19e5373c6dc38/linux-git-credential-github-keychain.zip
url="https://github.com/jakewilkins/git-credential-github-keychain/releases/download/$latest_release/${system}-git-credential-github-keychain.zip"
echo url:
echo $url

echo
echo
# exit
curl -Lo credential-helper.zip "$url"
unzip credential-helper.zip
mv -v git-credential-github-keychain ./bin/
rm credential-helper.zip

popd
