#!/bin/bash

ln -fs "$HOME/.config/p10k/p10k.zsh.linux" "$HOME/.p10k.zsh"

sudo apt update
sudo apt install -y jq luajit fzf ripgrep tmux universal-ctags


if [[ ! -f $HOME/bin/README.md ]]; then
	cd ~
	echo "Cloning bin repo"
	/usr/bin/git clone "https://github.com/jakewilkins/bin" bin-repo
	mv -v .dotfiles/bin/git-credential-github-keychain ./bin-repo/
	mv -v .dotfiles/bin/ghop ./bin-repo/
	rm -rf bin
	mv bin-repo bin
	cd -
fi

hash nvim 2>/dev/null || {
	# The apt installed version is 0.4.3, we'll just watch the minor version so they can
	# bump the patch version.
	minor_version=`nvim --version | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 2`

	if [[ "$minor_version" == "4" ]]; then
		curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
		chmod u+x nvim.appimage

		./nvim.appimage --appimage-extract >/dev/null

		sudo mv squashfs-root /
		sudo ln -fs /squashfs-root/AppRun /usr/local/bin/nvim
		rm nvim.appimage
		hash -r
	fi
}

echo "Installing vim plugins"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

if [ ! -d $HOME/.dotfiles/codespace-helpers ]; then
	echo "Installing codespace-helpers"
	$HOME/.dotfiles/script/install-codespace-helpers
fi

if [[ ! -d $HOME/.config/kitty/shell-integration ]]; then
	echo "Installing kitty helpers"

	# This is a redirect to the zip I created from my local install
	curl -LO https://jsw.io/JL9l7

	if [[ -f kitty-shell-integrations.zip ]]; then
		mkdir -p $HOME/.config/kitty/shell-integration/zsh
		mv kitty-shell-integrations.zip $HOME/.config/kitty/shell-integration/zsh

		pushd $HOME/.config/kitty/shell-integration/zsh
		unzip kitty-shell-integrations.zip
		rm -v kitty-shell-integrations.zip

		# This might be expected?
		export KITTY_INSTALLATION_DIR="$HOME/.config/kitty"

		# This is from the docs https://sw.kovidgoyal.net/kitty/shell-integration/#manual-shell-integration
		# and is also in my zshrc, running it here to hopefully get it in the current shell
		export KITTY_SHELL_INTEGRATION="enabled"
		autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
		kitty-integration
		unfunction kitty-integration

		popd
	fi
fi
