#!/bin/bash

ln -fs "$HOME/.config/p10k/p10k.zsh.linux" "$HOME/.p10k.zsh"

sudo apt update
sudo apt install -y jq luajit fzf ripgrep tmux

cd ~

/usr/bin/git clone "https://github.com/jakewilkins/bin" bin-repo
mv .dotfiles/bin/git-credential-github-keychain ./bin-repo/
rm -rf bin
mv bin-repo bin

cd -

hash nvim 2>/dev/null || {
	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	chmod u+x nvim.appimage

	./nvim.appimage --appimage-extract >/dev/null

	sudo mv squashfs-root /
	sudo ln -fs /squashfs-root/AppRun /usr/local/bin/nvim
	rm nvim.appimage
}

if [[ "$GITHUB_REPOSITORY" == "github/github" ]]; then
  sed -i "s|/.codespaces/bin/gitcredential_github.sh|$HOME/bin/git-credential-github-keychain|g" /etc/gitconfig
fi

echo "Installing vim plugins"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
