name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request: []
jobs:
  syntax:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: fish-actions/install-fish
      uses: fish-actions/install-fish@v1.1.0

    - name: Validate syntax
      run: fish -n config/fish/**/*.fish
