name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request: []
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Validate syntax
      run: fish -n config/fish/**/*.fish

    - name: Test script/setup
      run: bash script/setup

    - name: Test config.fish
      run: fish -c "source ~/.config/fish/config.fish"
